---
title: "EMA-CleanR"
author: "Sarah Sperry; Victoria Murphy."
date: "2025-12-05"
abstract: "Efficient pre-processing, cleaning, and visualization of Ecological Momentary Assessment (EMA) survey data in R to enable high-quality, real-time behavioral insights. Learn more at: https://github.com/DepressionCenter/EMA-CleanR"
params:
  inputFile: "EMA-Data.csv"
  inputFileHasHeaders: TRUE
output:
  html_document:
    code_folding: show
    theme: default
    highlight: textmate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    number_sections: true
    df_print: paged
    css: "styles/um-style.css"
    self_contained: true
---

<!--
This file is part of EMA-CleanR
EMA-CleanR.rmd
Author(s): Sarah Sperry; Victoria Murphy.
Created: 2025-12-05
Summary: Efficient pre-processing, cleaning, and visualization of Ecological Momentary Assessment (EMA) survey data in R to enable high-quality, real-time behavioral insights.
Notes: See README file for documentation and full license information.

Copyright © 2025 The Regents of the University of Michigan
 
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>.
-->

```{r setup, include=FALSE}
# Global chunk options
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE
)
```

----

# Project Setup
## Load Required Packages
```{r load-packages}

# Load required packages
# Refer to each package for their individual license
library(dplyr)
library(psych)
library(tidyverse)
library(lubridate)
library(table1)
library(corrplot)
library(ggplot2)
library(patchwork)
library(rlang)
```

## Set Project Parameters
```{r set-parameters}
# ---- Input Parameters ----
# If using R Markdown (.Rmd), set the parameters at the top of this file in YAML.
# To re-use this script outside R Markdown, set your values here.
inputFile <- if (exists("params") && !is.null(params$infile)) params$infile else "ema-data.csv"
inputFileHasHeaders <- if (exists("params") && !is.null(params$header)) params$header else TRUE
```

## Load Data Sets
```{r load-data}
# Read in data set 
EMAwide.merge <- read.csv(inputFile, sep = ",", header=inputFileHasHeaders)

cat("Number of rows loaded:", nrow(EMAwide.merge), "\n")
```

----

# Do Stuff
## Sub heading
```{r }
print('Coming soon!') # Code will be available soon.
```

## Sub heading
```{r }
print('Coming soon!') # Code will be available soon.
```



----

# License
## Copyright Notice
Copyright © 2025 The Regents of the University of Michigan


## Software and Library License Notice
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0-standalone.html>.


## Documentation License Notice
Permission is granted to copy, distribute and/or modify this document 
under the terms of the GNU Free Documentation License, Version 1.3 
or any later version published by the Free Software Foundation; 
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. 
You should have received a copy of the license included in the section entitled "GNU 
Free Documentation License". If not, see <https://www.gnu.org/licenses/fdl-1.3-standalone.html>



## Citation
If you find this repository, code or paper useful for your research, please cite it.


----

Copyright © 2025 The Regents of the University of Michigan
